[project]
name = "healthcare-ai-dq"
description = "Graph Transformer Autoencoder for anomaly detection in healthcare data using Synthea."
version = "0.1.0"
requires-python = ">=3.9"

[tool.uv]
# uv will use requirements.txt for dependencies
